### ISSUE TITLE
Backup using SDMMobiledevice 

### ISSUE THREAD

**Issue by sud27** [samdmarshall/SDMMobileDevice#101]
I can not figure out how to take backup using SDMMobileDevice. 
Any Sample code or any suggestion.
 
Thanks

**Comment by samdmarshall** [comment]
Please only open issues if they pertain to functionally problems with the code, I only have enough time to maintain this library as it is -- not write significant amounts of new code with it.

**Comment by sud27** [comment]
Thank you.

**Comment by sud27** [comment]
Hi Samdmarshall,

Hope you are doing well.


I looked into this link: “
https://github.com/samdmarshall/iOS-Internals/tree/master/mobilebackup
<%5Cl%20%22%22>”.

But it is looking for parsing “Manifest.mbdb” file. i think it is not that
i am looking for.
Actually I want to when i connect my iOS device to mac system then i want
to take a backup on my mac system (/MobileSync/Backup/).

I also used “AMSVC_BACKUP2” for backup. but not get success.


-(void)getMobileBackup
{
InitializeSDMMobileDeviceClasses();
connect = SDMMD_AMDeviceConnect(device);
connect = SDMMD_AMDeviceStartSession(device);

sdmmd_return_t result1 = kAMDInvalidArgumentError;
CFDictionaryRef dict = NULL;
SDMMD_AMConnectionRef conn = NULL;
conn = SDMMD_AMDServiceConnectionCreate(0, NULL, dict);
result1 = SDMMD_AMDeviceStartService(device, CFSTR(AMSVC_BACKUP2), NULL,
&conn);

if (SDM_MD_CallSuccessful(result1))
{
CFMutableDictionaryRef responset = NULL;
CFMutableDictionaryRef optionDict = SDMMD_create_dict();
CFDictionarySetValue(optionDict, CFSTR(kBackupDomain),
CFSTR(kLastCloudBackup));

result1 = SDMMD_ServiceSendMessage(SDMMD_TranslateConnectionToSocket(conn),
optionDict, kCFPropertyListXMLFormat_v1_0);
if (SDM_MD_CallSuccessful(result1))
{
result1 =
SDMMD_ServiceReceiveMessage(SDMMD_TranslateConnectionToSocket(conn),
(CFPropertyListRef *)&responset);

}
if (SDM_MD_CallSuccessful(result1))
{
NSMutableDictionary *dictResponse = (__bridge NSMutableDictionary
*)(responset);
NSLog(@"dictResponse=%@",dictResponse);
}
}
}



Please any help to be very appreciated. Looking forward for your kind
response.

Thanks

Sudhanshu


On Tue, Jan 17, 2017 at 8:51 PM, Samantha Marshall <notifications@github.com
