### ISSUE TITLE
dyld: Library not loaded: build/libSDMMobileDevice.dylib

### ISSUE THREAD

**Issue by daviyang35** [samdmarshall/SDMMobileDevice#105]
env:
```
 Host : Mac OS X 10.12.4 (16E195)
 Xcode : 8.3.1 (8E1000a)
 Git : git version 2.11.0 (Apple Git-81)
```
commit 995b9265edc29257414d76cdce6f6fd3275269e1
build framework with: make framework
output:
```
libCore.a
libSDMMobileDevice.dylib
libcrypto.a
libssl.a
```
add 4 files to xcode Mac OS project, build and run.
debug console output this,and app did not run.
```
dyld: Library not loaded: build/libSDMMobileDevice.dylib
```

**Comment by samdmarshall** [comment]
This isn't a problem with the framework or my code, but of your build configuration.
