### ISSUE TITLE
Not able to list down installed applications ?

### ISSUE THREAD

**Issue by antonyjoemathew** [samdmarshall/SDMMobileDevice#106]
After listiing my device using list.h , I tried to call `void LookupAppsOnDevice(char *udid)`. but not able to get the application list. Any suggestion ? I am trying to list down all the applications and take backup of some apps

Thanks

**Comment by samdmarshall** [comment]
I don't know if those services are still available in the same way or not. They may require changes, i'm not really in a position to do that active maintenance work anymore; please open a PR if you can figure this out.
