### ISSUE TITLE
Build the source

### ISSUE THREAD

**Issue by blakdragan7** [samdmarshall/SDMMobileDevice#107]
I have a question about building SDMobileDevice. On the Readme.me it mentions using the framework version of the project, however; I can not seem to build a framework version. I can only build a dylib or .a file. Am I doing something wrong or is the Readme just out of date and we should be using the dylib ?

**Comment by samdmarshall** [comment]
correct; the read-me is out of date and it now will build a static library (.a) or dynamic library (.dylib).
