### ISSUE TITLE
AMDeviceStartService returns useless AMConnectionRef after device has auto shut off

### ISSUE THREAD

**Issue by JeremyAgost** [samdmarshall/SDMMobileDevice#28]
Expected Behavior:
- AMDeviceStartService returns result other than kAMDSuccess if service cannot be negotiated due to the device have auto-shut-off after the lockdown session was established
- **or**
- AMDeviceStartService returns kAMDSuccess with AMConnectionRef that can be used to receive data

Actual Behavior:
* AMDeviceStartService returns kAMDSuccess with non-null AMConnectionRef but SDMMD_ServiceReceive calls with that connection time out

Repro steps:
1. Attach to awake connected device
2. Start lockdown session with AMDeviceStartSession
3. Wait until device auto shuts off
4. Attempt to start service with AMDeviceStartService
5. Get the socket struct by calling SDMMD_TranslateConnectionToSocket() on the AMConnectionRef returned
6. Call SDMMD_ServiceReceive. Function returns kAMDSuccess but data parameter is not set, indicating timeout.

**Comment by samdmarshall** [comment]
@JeremyAgost what is the status of this, can it be closed?
