### ISSUE TITLE
EXC_BAD_ACCESS in SDMMD_Service.c

### ISSUE THREAD

**Issue by mountsi** [samdmarshall/SDMMobileDevice#62]
I'm experiencing some random crashes when using the SDMMobileDevice framework.
(EXC_BAD_ACCESS in SDMMD_Service.c SDMMD__ServiceReceiveBytesSSL)
I'm not able to replicate this but experiencing this regularly.

![screenshot](https://cloud.githubusercontent.com/assets/9379112/5331500/1b419b52-7e2e-11e4-877d-18962491190a.png)

**Comment by mountsi** [comment]
It's been a while but I found an interesting issue.
Using SendDeviceCommand() the command SDMMD_ServiceReceiveMessage will receive the result 0x00 (ok) message.
After sending this command 100 times (replicable), the result 0xe8000013 (kAMDInvalidResponseError) is received.
I'm using a NSTimer with a 5 sec interval to test this.

**Comment by samdmarshall** [comment]
Is this a separate issue from the EXC_BAD_ACCESS crash? If so could you please open a new issue for it? If it is related to this existing issue could you gist the code for a reproducible case so I can have a look and test it myself?

**Comment by mountsi** [comment]
Kind of related, because of this problem my original code will cause this EXC_BAD_ACCESS.
I'm still checking what's going on there but one at a time.
I'll prepare a sample code and open a new issue.

**Comment by samdmarshall** [comment]
Requesting an update on this issue. As I understand it, you are being presented with an error code stating the socket is no longer valid before calling a method that accesses the socket again -- which causes a crash. If that is the case, then I am not sure what I can do about that as you seem to be calling a read/write on an invalid socket.

**Comment by mountsi** [comment]
Commit c657072 solved the initial issue, the other problems were covered by own issues. 
So this issue can be closed.
