### ISSUE TITLE
Connect to device fails after about 90 requests

### ISSUE THREAD

**Issue by mountsi** [samdmarshall/SDMMobileDevice#69]
The sample code provided here https://github.com/mountsi/sample1 will stop working after about 90 requests.
I also saw an issue that SDMMD_ServiceReceiveMessage returns some error codes after about 100 (or 30 on other devices) tries but I wasn't able to create a reproducable sample yet.

Please try the mentioned sample.

![screenshot](https://cloud.githubusercontent.com/assets/9379112/5893408/ea517662-a4e2-11e4-9a39-8c55f4637b77.png)

**Comment by samdmarshall** [comment]
Looking briefly at the SDMMD_AMDeviceConnect code, you should get an error message printed out if there is a fairly to connect except in the following cases:
1) device object fails SDMMD_AMDeviceIsValid() and the return code then becomes kAMDDeviceDisconnectedError
2) socket returned from SDMMD__connect_to_port() is invalid (-1)
3) error in establishing a connection with lockdown service daemon, return code becomes kAMDNoResourcesError

Knowing what the returned error code from the connection attempt would help to narrow down the cause of this.

Your sample code for this comes without a project file, so I'm going to need to set aside time this week to configure and setup the code alongside the current version of the framework to try to debug it. If you can upload a complete sample project and environment for this i'd be able to get to it much sooner.

**Comment by mountsi** [comment]
I updated the sample project
The returned code is kAMDNoResourcesError followed by a kAMDDeviceDisconnectedError at the next attempt
![screenshot2](https://cloud.githubusercontent.com/assets/9379112/5893610/1c8a354e-a4eb-11e4-8caf-29d088ccfeaf.png)

**Comment by samdmarshall** [comment]
I cannot repro the issue of failing to connect to the device after trying multiple times with your sample code. I can, however, reproduce the original crash on the 100th request twice now. Both times show an incomplete backtrace in the debugger and garbage values so I feel like there is something else going on here. This issue might be device related so I'm going to leave it open until i can try to repro with other hardware.

**Comment by samdmarshall** [comment]
Can you redo this sample again without making it re-fetch the device object multiple times per call? That function wasn't intended to be called frequently, if you can modify the code to make it pass the existing device object you have through and not make it query again that would be helpful to debug this, and another problem that was run into using the same sample code.

**Comment by mountsi** [comment]
I tracked down the cause to the SDMMD_AMDeviceStartSession / SDMMD_AMDeviceStopSession calls.
Without these calls the sample seems to run fine at the moment, I'll do some further testing the next days

**Comment by samdmarshall** [comment]
ok cool, thanks!

**Comment by mountsi** [comment]
Looking at "SDMMD_AMConnectionRef AttachToDeviceAndService(SDMMD_AMDeviceRef device, char *service)" in iOSConsole/attach.c:
Is it intended that "SDMMD_AMDeviceStopSession(device);" and "SMMD_AMDeviceDisconnect(device);" are only called if SDMMD_AMDeviceStartService fails? (line 75+)

At the moment "SendDeviceCommand" (in iOSConsole/power.c) is calling AttachToDeviceAndService which will do a DeviceConnect and a DeviceStartSession but never a DeviceStopSession and DeviceDisconnect.
So every SendDeviceCommand call will leave a started session and an opened device connection open.
If you run SendDeviceCommand multiple times these open states could cause the mentioned problems.

(SendDeviceCommand and AttachToDeviceAndService code from my sample code is mostly copies from the iOSConsole sample)

**Comment by samdmarshall** [comment]
Which is why i mentioned the code wasn't intended to be run this many times consecutively. If you can, please attempt to replicate this issue without using my sample code as a base.

**Comment by mountsi** [comment]
After testing with the modified sample code I'm experiencing the same issue but after a longer time period.
It seems the modifications (stopping the session and closing the connection) increases the possible connection count.

Issue still the same but I tracked it down to the SDMMD_ServiceReceiveMessage call.
In my sample with my setup after 127 rounds (repeatable) SDMMD_ServiceReceiveMessage always returns kAMDSendMessageError

The interesting part: Using an other iOS device the issue appears after 147 rounds (repeatable)

**Comment by samdmarshall** [comment]
Can you confirm that the code does return an error prior to a reproducible crash?

**Comment by mountsi** [comment]
I did not experienced a crash with the sample code yet, the kAMDSendMessageError appears regulary

**Comment by samdmarshall** [comment]
I think I have lost what this particular issue is about anymore. Have we moved past the original crash issue and are addressing the error code response or is this still related to the original crash mentioned? If this is a new issue i'd like to close this and open a new issue ticket with only relevant information. Thanks.

**Comment by mountsi** [comment]
You're right, as the crash does not appear any more this issue can be closed
