### ISSUE TITLE
.app using the framework will crash on systems without Xcode

### ISSUE THREAD

**Issue by mountsi** [samdmarshall/SDMMobileDevice#70]
The sample code https://github.com/mountsi/sample1 works fine.
However, when creating an .app from this code this .app will only run on OS X with installed Xcode.
Running this .app on an OS X without Xcode installed will cause a crash. (tried in VMware and also on a MacBook directly)

I'm not really sure why this is happening or if I forgot something important but I can replicate this issue any time.
After installing Xcode on OS X the .app is working fine instantly.

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   com.apple.CoreFoundation      	0x00007fff8570c7a6 CFGetTypeID + 54
1   com.samdmarshall.SDMMobileDevice	0x0000000109d821d7 SDMMD__CopyEscrowBag + 151
2   com.samdmarshall.SDMMobileDevice	0x0000000109d839ab SDMMD_AMDeviceStartSession + 619
3   com.test.bugtest              	0x0000000109d69861 0x109d67000 + 10337
4   com.apple.Foundation          	0x00007fff8b47f784 _NSFireTimer + 96
5   com.apple.CoreFoundation      	0x00007fff857953e4 _CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
6   com.apple.CoreFoundation      	0x00007fff85794f1f __CFRunLoopDoTimer + 1151
7   com.apple.CoreFoundation      	0x00007fff858065aa __CFRunLoopDoTimers + 298
8   com.apple.CoreFoundation      	0x00007fff857506a5 __CFRunLoopRun + 1525
9   com.apple.CoreFoundation      	0x00007fff8574fe75 CFRunLoopRunSpecific + 309
10  com.apple.HIToolbox           	0x00007fff8d367a0d RunCurrentEventLoopInMode + 226
11  com.apple.HIToolbox           	0x00007fff8d3677b7 ReceiveNextEventCommon + 479
12  com.apple.HIToolbox           	0x00007fff8d3675bc _BlockUntilNextEventMatchingListInModeWithFilter + 65
13  com.apple.AppKit              	0x00007fff886ee24e _DPSNextEvent + 1434
14  com.apple.AppKit              	0x00007fff886ed89b -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 122
15  com.apple.AppKit              	0x00007fff886e199c -[NSApplication run] + 553
16  com.apple.AppKit              	0x00007fff886cc783 NSApplicationMain + 940
17  libdyld.dylib                 	0x00007fff85ffd5fd start + 1

**Comment by samdmarshall** [comment]
Have you tried this using the latest checkout from master? This crash log looks very similar to a crash I was shown and fixed the other day.

**Comment by mountsi** [comment]
Sorry for the delay, I reinstalled everything to make sure.
You're right, the latest commit fixed the issue. Interesting behaviour that with existing Xcode installation the issue does not exist... Sorry for the confusion.
