### ISSUE TITLE
SDMMD_ServiceReceiveMessage always returns kAMDSendMessageError when called multiple times

### ISSUE THREAD

**Issue by mountsi** [samdmarshall/SDMMobileDevice#71]
Sample code provided here https://github.com/mountsi/sample1

After calling SDMMD_ServiceReceiveMessage multiple times (in my case either 147 times on an ipad 4 and 120 times on an iphone 5) the method always returns kAMDSendMessageError instead of kAMDSuccess. These counts are reproducible.

![screenshot1](https://cloud.githubusercontent.com/assets/9379112/6251936/192e5e52-b797-11e4-8bcf-576a639b1e8d.png)

![screenshot2](https://cloud.githubusercontent.com/assets/9379112/6251939/1cb6c5a0-b797-11e4-98ab-3c7e2151f391.png)

**Comment by samdmarshall** [comment]
I was able to reproduce this behavior, checking the device's syslog at the same time I am noticing it print:
`lockdownd [26] <Error>: Could not set socket option SO_OPPORTUNISTIC: Invalid argument` on each request, and then `kernel [0] <Notice>: proc: table is full` after it starts returning kAMDErrorError from the device. This error code only returns when the socket times out, so I'm going to guess that the command you are issuing needs another message to close the session or otherwise terminate the service.

**Comment by mountsi** [comment]
I agree.
The worse problem here is that in this state all memory on the iOS device is used and iOS on the device might crash anytime.
I did not find anything in the framework that looks like it's closing something that isn't closed with a SDMMD_AMDeviceDisconnect.
I'm not into the framework too deep but I assume a SDMMD_AMDeviceDisconnect should close any connection to the device?

I also noticed that closing the application will free up the used memory on the device instantly (close all existing connections), this confirms that with every call an connection is opened but not closed

**Comment by samdmarshall** [comment]
Closing a connection with a device will not stop service connections. My suggestion would be to stop polling for devices and starting new services each time your timer fires and continue to use the same device object.

**Comment by mountsi** [comment]
Saving the socket object returned by SDMMD_TranslateConnectionToSocket and reuse it every time needed I found out the most practical solution for me.
Does something speak against this?

**Comment by samdmarshall** [comment]
no, you should be holding onto the connection object. `SDMMD_TranslateConnectionToSocket` exists just as a means of convenience to access the internal socket, you need to keep the connection object around to close it properly.

**Comment by samdmarshall** [comment]
Hey, i saw you pop into the irc channel to ask about how to release the SDMMD_AMConnectionRef object, simply call CFRelease() on the object and it will close the existing connection. Since connection objects are single-use there isn't a point of keeping it around without a valid socket.

**Comment by mountsi** [comment]
This should do the trick, thanks!
Keeping the connection object and using it later solves the issue.
