### ISSUE TITLE
iosdeploy lldb support seems incomplete

### ISSUE THREAD

**Issue by ryu2** [samdmarshall/SDMMobileDevice#77]
When I do  `iosdeploy -d <udid> -a <path to my .app file>`

it installs OK and I can launch manually from my device, but then I get this when it spawns lldb:

```
  (lldb) target create "/tmp/sdmmd-lldb-prep"
error: '/tmp/sdmmd-lldb-prep' doesn't contain any 'host' platform architectures: x86_64h, x86_64, i386
```

(lldb)

Looking at `/tmp/sdmmd-lldb-prep` and `iosdeploy/main.c` it looks like a lot of the variables aren't expanded, and lldb prep commands missing.  Is this something you're actively working on now.  If not, happy to do this and submit a PR.  Thanks!

**Comment by samdmarshall** [comment]
Yes! it isn't complete yet, i never got around to finishing it. If you want to submit a PR for adding that support that would be awesome.
