### ISSUE TITLE
#include path in internal headers is inconsistent

### ISSUE THREAD

**Issue by ryu2** [samdmarshall/SDMMobileDevice#79]
In various `*Internal.h` headers I see

    #include <SDMMobileDevice/CFRuntime.h>

and

    #include "CFRuntime.h"

and also

    #if IS_FRAMEWORK
    #include <SDMMobileDevice/CFRuntime.h>
    #else
    #include "CFRuntime.h"
    #endif

This is causing issues when I'm integrating this into a bigger project with its own build scripts.  Should we unify them?  I suggest the second variant, since `#include <...>` should really be reserved for system libraries (per most C style guides).

**Comment by samdmarshall** [comment]
No, as I believe that exists for the embedded Linux builds of this library.
