### ISSUE TITLE
Add support for iPhone 6/6 Plus/6S/6S Plus ?

### ISSUE THREAD

**Issue by wzqcongcong** [samdmarshall/SDMMobileDevice#80]
In `SDMMD_Functions.h`, it only supports up to `{"iPhone6,2", "iPhone 5S"}`, so any plan to support new iPhone 6/6 Plus/6S/6S Plus? Thanks!

**Comment by samdmarshall** [comment]
PRs are welcome as I don't have much time to work on doing much beyond maintaining the code that is currently in the repo.
