### ISSUE TITLE
Publish on brew

### ISSUE THREAD

**Issue by Coneko** [samdmarshall/SDMMobileDevice#81]
Is there any interest in having the command line utilities published to Brew?

**Comment by samdmarshall** [comment]
I'm going to do that once https://github.com/Homebrew/homebrew/issues/43865 is resolved.

**Comment by samdmarshall** [comment]
You are now able to install iOSConsole via

```
$ brew tap samdmarshall/formulae
$ brew update
$ brew install samdmarshall/formulae/iosconsole
```

**Comment by Coneko** [comment]
Nice thanks!
