### ISSUE TITLE
accessing the .GeneralPreferences.plist in the mobile directory

### ISSUE THREAD

**Issue by jorgeleo** [samdmarshall/SDMMobileDevice#82]
Hi,

Trying to use the SDMMobileDevice to access the .GeneralPreferences.plist and I cannot figure out how... any ideas?

Jorge

**Comment by samdmarshall** [comment]
I haven't tried to access that file myself, depending on what version of iOS you are using it may be inaccessible due to tightening of access around files on the device. Could you elaborate on what you have done to try to get access to this file so far?

**Comment by jorgeleo** [comment]
to change values in that file, I have been modifying a backup and then restoring only that file (tricky, but doable)

But that path makes a reboot of the device that I want to avoid.

**Comment by samdmarshall** [comment]
A reboot is not required immediately after you apply a partial backup, you can delay it such that it can preserve the changes to be applied after the next reboot happens (this was defined behavior in iOS 8 and earlier, I don't know about iOS 9 yet)

**Comment by jorgeleo** [comment]
I tried that, but the fact that the changes are not applied until the next reboot does not help me to avoid the reboot, and because the things I do after, I cannot delay it. Which is why I though, maybe there is a property list service that take the new values and applies them immediately.

**Comment by samdmarshall** [comment]
I do know that some changes can be applied pre-reboot using that method but this is apparently not one of them. In that case I don't know if there is a way to forcefully reload that without a reboot. This isn't the most inconvenient thing as you can command it to reboot via the power diagnostic service.

**Comment by jorgeleo** [comment]
can you? how?

Sent from Outlook




On Wed, Oct 14, 2015 at 3:59 PM -0700, "Samantha Marshall" <notifications@github.com> wrote:












I do know that some changes can be applied pre-reboot using that method but this is apparently not one of them. In that case I don't know if there is a way to forcefully reload that without a reboot. This isn't the most inconvenient thing as you can command it to reboot via the power diagnostic service.

**Comment by samdmarshall** [comment]
https://github.com/samdmarshall/SDMMobileDevice/blob/master/iOSConsole/iOSConsole/power.c

**Comment by samdmarshall** [comment]
Closing this as it hasn't been updated in a while and seems resolved.

**Comment by jorgeleo** [comment]
thank you for closing it and for your time. unfortunately for the flags to be applied I have to reboot immediately :(
