### ISSUE TITLE
How do I take backup and restore from it? Any sample code?

### ISSUE THREAD

**Issue by bilawal230** [samdmarshall/SDMMobileDevice#83]
Any sample code to take backup using mobilebackup2 service? I can't figure how to use it.

**Comment by samdmarshall** [comment]
There is code in the framework for restoring files from a backup, the header documents most of the communication process. I don't think I have implemented the code to download a backup from the device yet.

**Comment by bilawal230** [comment]
Thanks, i will look into it.

**Comment by sud27** [comment]
@bilawal230  Could you help how can we take backup using mobilebackup2 service ?
