### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by Kalvin126** [samdmarshall/SDMMobileDevice#87]
I am trying to build the .framework but all the files in the core folder in the .xcodeproj are missing?
![screen shot 2016-03-15 at 11 35 45 am](https://cloud.githubusercontent.com/assets/5943523/13789616/16558dba-eaa2-11e5-89d7-7c3d5f07c232.png)

**Comment by samdmarshall** [comment]
You need to check out the submodule.

**Comment by Kalvin126** [comment]
Ah I did not see the .gitmodule file. Thanks!
