### ISSUE TITLE
SDMMD_AMDeviceCopyValue on non existing key crashes on swift

### ISSUE THREAD

**Issue by mountsi** [samdmarshall/SDMMobileDevice#89]
I'm getting an EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP) crash when trying to use SDMMD_AMDeviceCopyValue with a key on a device which does not support the key (like phone number on iPod)
Running the code in objective-c will cause a console log but no crash while using the code below in swift will cause the crash.

```
var result1: sdmmd_return_t = SDMMD_AMDeviceConnect(deviceRef)
var result2 = SDMMD_AMDeviceStartSession(deviceRef)

var key = CFStringCreateWithCString(kCFAllocatorDefault, kPhoneNumber, 0)
var pn = SDMMD_AMDeviceCopyValue(deviceRef, kGlobalDomain, key)
print(pn.takeUnretainedValue())

var result3 = SDMMD_AMDeviceStopSession(device)
var result4 = SDMMD_AMDeviceDisconnect(device)

```
Call in obj-c
`NSLog(@"%@",(NSString*)CFBridgingRelease(SDMMD_AMDeviceCopyValue(device, NULL, CFSTR(kPhoneNumber))));`

**Comment by samdmarshall** [comment]
Where does the crash trace place the issue? If this is into swift then there is nothing I can do about it. Due to this not happening in objective-c I am leaning towards saying this is not the fault of my library.

**Comment by mountsi** [comment]
You're right - the trace showed a problem in swift not in your library. 
Sorry for any confusion and keep up the good work!

**Comment by samdmarshall** [comment]
You should be opening an issue on this with the swift team, I'm not sure if it is improper usage of the API or an actual problem with swift though.
