### ISSUE TITLE
SDMMD_lockssl_handshake: SSL handshake fatal lower level error 5 when using iOS 10 beta

### ISSUE THREAD

**Issue by mountsi** [samdmarshall/SDMMobileDevice#91]
Seems that Apple changed something in iOS 10 beta 4, up to beta 3 everything worked fine
```
./iOSConsole -l
Currently connected devices: (1)
SDMMD_lockssl_handshake: SSL handshake fatal lower level error 5: (null).
SDMMD_AMDeviceStartSession: Could not start session with device 581: kAMDInvalidResponseError
```

**Comment by samdmarshall** [comment]
Interesting, not much can be done until the official iOS 10 release, if you want to research and contribute a fix that would be awesome -- I am not planning on installing any of the betas.

**Comment by mountsi** [comment]
I'm not into SSL but I could follow the error to 
`SSL *SDMMD_lockssl_handshake(uint64_t socket, CFTypeRef hostCert, CFTypeRef deviceCert, CFTypeRef hostPrivKey, uint32_t num)
`
in SDMMD_AMDevice.c

The Line
`						result = SSL_do_handshake(ssl);
`
results -1 which means a

>  The TLS/SSL handshake was not successful because a fatal error occurred either at the protocol level or a connection failure occurred

(due to https://www.openssl.org/docs/manmaster/ssl/SSL_do_handshake.html)

The line
`							uint32_t err = SSL_get_error(ssl, result);
`
returns a SSL_ERROR_SYSCALL which means

> Some I/O error occurred

(due to https://www.openssl.org/docs/manmaster/ssl/SSL_get_error.html)
As result is 0 here we are now at 

> If ret == 0, an EOF was observed that violates the protocol

which brings me to the end of my debugging skill.
Hope this helps

Maybe an issue with the openssl version which is added (openssl-0.9.8zg) or Apple changed something on their implementation

**Comment by samdmarshall** [comment]
This would require looking at the `lockssl_handshake` function in MobileDevice.framework to see if there are auth changes to that code, if so then the library needs to be updated. I find it unlikely to have a major change without a version check first. if it works with existing iTunes or Xcode versions without an update then it is unlikely there was a change. Much of the auth exchange is immutable as it would cause breakages across all the old devices too.

**Comment by mountsi** [comment]
With this in mind I've also checked macOS 10.12 beta and it seems that with this beta the same issue also occurs using iOS 9 (and also 10 beta)
It seems that apple is currently touching this on every OS

**Comment by mountsi** [comment]
It seems that apple now requires tls seems to cause the problems here
https://developer.apple.com/library/prerelease/content/releasenotes/General/WhatsNewIniOS/Articles/iOS10.html

**Comment by samdmarshall** [comment]
The contents of the developer SDK don't apply to the private frameworks, I would like to see a new version of the MobileDevice framework and disassembly to see the differences in the function I mentioned.

**Comment by samdmarshall** [comment]
Someone was able to provide me with a copy of the MobileDevice.framework from the latest beta, from a cursory examination, i don't see very much if any difference in the auth procedure. I do notice that this like (https://github.com/samdmarshall/SDMMobileDevice/blob/master/Framework/MobileDevice/Device%20Types/AMDevice/SDMMD_AMDevice.c#L164) is `SSLv23_method()` instead of `SSLv3_method()`. You could try that change in your own code and see if that works.

**Comment by samdmarshall** [comment]
Also, error 5 is:
```
# define SSL_ERROR_SYSCALL               5/* look at error stack/return
                                           * value/errno */
```

so this should be able to be something you can debug if you build and set breakpoints and check those values after attempting to connect.

**Comment by mountsi** [comment]
It seems apple dropped support for ssl3 and requires tls instead. Using beta 4 and tls works fine. It seems this changes from beta to beta the best would be waiting for the final release and set the connection method appropriately.

**Comment by kapil0408** [comment]
It solved my problem for 10.0.1 version

Thanks

**Comment by samdmarshall** [comment]
@kapil0408 I would ask that you please refrain from posting into closed issues, it alerts all people that have previously posted in the issue and doesn't add any new dialogue about the issue. Thanks.

**Comment by kapil0408** [comment]
Ok, I will not post in any things in closed issues.
