### ISSUE TITLE
<openssl/opensslconf.h> is not found

### ISSUE THREAD

**Issue by kapil0408** [samdmarshall/SDMMobileDevice#94]
I am using Xcode 7.3.1 with OS X El Capitan 10.11.6.
When i build this then i found "<openssl/opensslconf.h> is not found"

Plz help me to fix it.
Thanks

**Comment by samdmarshall** [comment]
does this solve your issue? https://github.com/samdmarshall/SDMMobileDevice/issues/72

**Comment by kapil0408** [comment]
Hi,

Exactly what i did,  First i opened "SDMMobileDevice.workspace" then build "Openssl" it woked fine.
then i build "SDMMobileDevice-Framework" also it worked fine and go to Product and copy "SDMMobiledevice.framwork" from Debug folder.

And also build "libSDMMobileDeviceStatic.a" file and copy "libSDMMobileDeviceStatic.a" from Debug folder

Then i created a demo application and copy "SDMMobileDevice framework" and "libSDMMobileDeviceStatic.a" into my project as described by you also. 

Getting this error when i run project.
dyld: Library not loaded: @rpath/SDMMobileDevice.framework/SDMMobileDevice
  Referenced from: /Users/admin/Library/Developer/Xcode/DerivedData/TestingDemo-hahksuuanirawvgrcidmtokpkdqk/Build/Products/Debug/TestingDemo.app/Contents/MacOS/TestingDemo
Reason: image not found

Please help me to fix it.
Many Thanks.

**Comment by kapil0408** [comment]
I solved it my error. :)
