### ISSUE TITLE
Calling 'SDMMD_TranslateConnectionToSocket' with incomplete return type 'SocketConnection' (aka 'struct SocketConnection_Internal')

### ISSUE THREAD

**Issue by kapil0408** [samdmarshall/SDMMobileDevice#96]
Hi,

I am using this code in my project.

   sdmmd_return_t result = kAMDInvalidArgumentError;
    CFDictionaryRef dict = NULL;
    SDMMD_AMConnectionRef conn = SDMMD_AMDServiceConnectionCreate(0, NULL, dict);
    result1 = SDMMD_AMDeviceSecureStartService(device, CFSTR(AMSVC_SYSLOG_RELAY), NULL, &conn);
    if (SDM_MD_CallSuccessful(result))
    {
        NSLog(@"success12");
        CFMutableDictionaryRef optionDict = SDMMD_create_dict();
        CFDictionarySetValue(optionDict, CFSTR("Request"), CFSTR("GasGauge"));
        
        result = SDMMD_ServiceSendMessage(SDMMD_TranslateConnectionToSocket(conn), optionsDict, kCFPropertyListXMLFormat_v1_0);
        CFMutableDictionaryRef response;
        result = SDMMD_ServiceReceiveMessage(SDMMD_TranslateConnectionToSocket(conn), (CFPropertyListRef *)&response);
        if (SDM_MD_CallSuccessful(result))
        {
            PrintCFType(response);
        }
    }
	
But it is warning on this line 
 “SDMMD_AMConnectionRef conn = SDMMD_AMDServiceConnectionCreate(0, NULL, dict);”
Warning: 
1. Implicit declaration of function 'SDMMD_AMDServiceConnectionCreate' is invalid in C99
2. Incompatible integer to pointer conversion initializing 'SDMMD_AMConnectionRef' (aka 'struct am_connection *') with an expression of type 'int'

And Error on this line: 
“result = SDMMD_ServiceSendMessage(SDMMD_TranslateConnectionToSocket(conn), optionsDict, kCFPropertyListXMLFormat_v1_0);”
Error;
1. Calling 'SDMMD_TranslateConnectionToSocket' with incomplete return type 'SocketConnection' (aka 'struct SocketConnection_Internal')

I tried to solve this but not get to success
Please help to fix it.

Thanks

**Comment by kapil0408** [comment]
Please any suggestion......

**Comment by samdmarshall** [comment]
It sounds like you are missing header imports or are using the framework code incorrectly. This project is in maintenance mode atm, so the only changes I plan on addressing (if any) are functionality related.

**Comment by kapil0408** [comment]
Thanks for quick reply. I look into it and get back to you.

**Comment by kapil0408** [comment]
I solved error and warning as above mentioned.
I included this in my file
#import <SDMMobileDevice/SDMMD_Service.h>
#import <SDMMobileDevice/SDMMD_Connection_Internal.h>

but when i build the project than it show #include<openssl/ssl.h> not found in SDMMD_Connection_Internal.h file.

Please help me to fix it.

**Comment by kapil0408** [comment]
I also included "openssl project" in my project and build this also alone it works fine then i build my project included above files but it is showing again "<openssl/ssl.h>" file not found.

**Comment by kapil0408** [comment]
I am using SDK 10.10 but not get succeed on openssl for 10.11. i will look this issue after.

**Comment by kapil0408** [comment]
-(void)getContainer
{
    CFDictionaryRef dict = NULL;
    SDMMD_AMConnectionRef conn = SDMMD_AMDServiceConnectionCreate(0, NULL, dict);
    
    sdmmd_return_t result = SDMMD_AMDeviceSecureStartService(device,  CFSTR(AMSVC_HOUSE_ARREST), NULL, &conn);
    if (SDM_MD_CallSuccessful(result))
    {
        CFMutableDictionaryRef optionsDict = SDMMD_create_dict();
        CFDictionarySetValue(optionsDict, CFSTR("Command"), CFSTR("VendContainer"));
        CFDictionarySetValue(optionsDict, CFSTR("Identifier"), CFSTR("com.demo.safe"));
        
        SocketConnection socket = SDMMD_TranslateConnectionToSocket(conn);
        
        result = SDMMD_ServiceSendMessage(socket, optionsDict, kCFPropertyListXMLFormat_v1_0);
        CFSafeRelease(optionsDict);
        if (SDM_MD_CallSuccessful(result))
        {
            CFMutableDictionaryRef response;
            result = SDMMD_ServiceReceiveMessage(socket, (CFPropertyListRef *)&response);
            if (SDM_MD_CallSuccessful(result))
            {
                if (SDM_MD_CallSuccessful(result))
                {
                    NSMutableDictionary *dictResponse = (__bridge NSMutableDictionary *)(response);
                    NSLog(@"dictResponse=%@",dictResponse);
                }
                
//                SDMMD_AFCConnectionRef afc = SDMMD_AFCConnectionCreate(conn);
//                if (afc)
//                {
//                    SDMMD_AFCConnectionRef afc = SDMMD_AFCConnectionCreate(conn);
//                    SDMMD_AFCProcessOperation(afc, &remove_old);
//                    char *copy_path = CreateCStringFromCFStringRef(remote_path);
//                    status = SDMMD_AMDeviceCopy(afc, (char *)[local_path UTF8String], "Documents/libReveal.dylib");
//                    SDMMD_AFCOperationRef move_op = SDMMD_AFCOperationCreateRenamePath(CFSTR("Documents/libReveal.dylib"), remote_path);
//                    SDMMD_AFCProcessOperation(afc, &move_op);
//                    free(copy_path);
//                }
            }
        }
    }
    SDMMD_AMDeviceStopSession(device);
    SDMMD_AMDeviceDisconnect(device);
}



i am getting for this fucntion:
dictResponse={
    Status = Complete;
}

Could you please tell me how to get container data for this particular app (com.demo.safe).
like Documents, Library, Tmp

Please help me :)

**Comment by samdmarshall** [comment]
This is not for StackOverflow style questions, it is for functionality or implementation issues with this library. I am going to close this thread as it doesn't seem like you have a problem with implementation anymore.

**Comment by kapil0408** [comment]
Yes, i am agree with you that is not for StackOverFlow style question.
But could you please give me some little suggestion on it.

Please....
Thanks.
