### ISSUE TITLE
AMSVC_FILE_RELAY (com.apple.mobile.file_relay)

### ISSUE THREAD

**Issue by kapil0408** [samdmarshall/SDMMobileDevice#97]
I read about this service and I am using this service for IOS 8.3 and OSX 10.10. then it is showing me in response:
{
    Error = PermissionDenied;
    Goodbye = 1;
}

Could you please tell me how to fix it.

I think this is not a StackOverFlow type question. i think it related to functionality and implementation type issue.

Please suggest.

**Comment by samdmarshall** [comment]
This services was disabled and requires additional configuration prior to use since iOS 8 https://support.apple.com/en-us/HT203034.

**Comment by kapil0408** [comment]
Thanks for reply. i checked this it is saying as exactly you said.

is there any possibilities to find out it in your library?

I also used House_arrest for system App and it is showing "InstallationLookUpFailed" for IOS 8.3 and OSX 10.10.

I read below url:

http://2013.hackitoergosum.org/presentations/Day3-04.Hacking%20apple%20accessories%20to%20pown%20iDevices%20–%20Wake%20up%20Neo!%20Your%20phone%20got%20pwnd%20!%20by%20Mathieu%20GoToHack%20RENARD.pdf

IMazing and PhoneClean app is doing as i want.

Please any favor on this.

Thanks

**Comment by kapil0408** [comment]
Ok. I will see this at my end.

Thanks :)
