### ISSUE TITLE
Does not support Xcode8

### ISSUE THREAD

**Issue by MartinLau7** [samdmarshall/SDMMobileDevice#98]
Hi, i using Xcode8, but Does not support Xcode8 Now.
sorry, my englist is poor.

**Comment by samdmarshall** [comment]
Thanks for filing this issue, this was not something I was aware of breaking. I think I should be able to address this during this next week and hopefully remove the dependency on Xcode for building this.

**Comment by MartinLau7** [comment]
Thanks for reply. I'll be waiting for your great update

**Comment by samdmarshall** [comment]
I have a preliminary version up in #100, if you could give that a go and confirm it works?

**Comment by MartinLau7** [comment]
I try to build the sdm_usbmuxd (#100) , but it doesn't seem to work

**Comment by samdmarshall** [comment]
Ok, that project doesn't yet have makefile support, I still have to do that and the unit tests.

Quoting MartinLau (2017-01-15 01:59:42)

**Comment by MartinLau7** [comment]
（https://github.com/heiby/iTools）
This source does not seem to be affected by iTunes and Xcode to see if it is helpful for your improvement

**Comment by samdmarshall** [comment]
I am migrating away from Xcode because I no longer use it as a primary development environment. As a result I don't have the tools installed to maintain this long-term as it is.

**Comment by MartinLau7** [comment]
ok, I'm trying not to rely on Xcode compiler constraints.

**Comment by samdmarshall** [comment]
This should be resolved now.
